### ISSUE TITLE
Fatal error: Uncaught TypeError

### ISSUE THREAD

**Issue by vikramsingh86** [PHPieces/anz-egate#3]
Hello sir,

I am using this script for processing payment with anz payment gateway. I have setup the script in my local environment(XAMPP) but when I execute the script, I am getting below fatal error.

_Fatal error: Uncaught TypeError: Argument 1 passed to PHPieces\ANZGateway\models\Card::__construct() must be of the type integer, string given in E:\xampp2\htdocs\anz\vendor\phpieces\anz-egate\src\models\Card.php:47 Stack trace: #0 [internal function]: PHPieces\ANZGateway\models\Card->__construct('403000001000123...', '2212', '123') #1 E:\xampp2\htdocs\anz\vendor\phpieces\anz-egate\src\models\Model.php(32): ReflectionClass->newInstanceArgs(Array) #2 E:\xampp2\htdocs\anz\vendor\phpieces\anz-egate\src\ChargeRequest.php(69): PHPieces\ANZGateway\models\Model::create(Array) #3 E:\xampp2\htdocs\anz\vendor\phpieces\anz-egate\src\Gateway.php(79): PHPieces\ANZGateway\ChargeRequest::create(Array) #4 E:\xampp2\htdocs\anz\index.php(27): PHPieces\ANZGateway\Gateway->send() #5 {main} thrown in E:\xampp2\htdocs\anz\vendor\phpieces\anz-egate\src\models\Card.php on line 47_

Please help me to solve this error.

Thanks

**Comment by jclyons52** [comment]
You have a type error, the first argument passed to the Card model was expected to be an integer, a string was given. 

Normally I would expect this conversion to have happened automatically for you, as PHP defaults to coercive types ranter than strict. Check your configuration and see it you have strict types enabled. otherwise, convert the string to an integer and it should work. 

Also the test are run against [php version 7.1](https://travis-ci.org/PHPieces/anz-egate) so I can't verify if there are issues with other php versions.

**Comment by vikramsingh86** [comment]
Hi jclyons52,

Thanks for your prompt reply.
Yes, it was type error and now it has been resolved. But I am unable to complete the transaction with any test cards. I am getting 'Invalid Card Number' error when I test it with test card 5123456789012346.
Please help.

Thanks

**Comment by jclyons52** [comment]
Invalid card number is a response from the api, those test cards are only for testing, the don't work with the live api. Consult the ANZ api docs
